### PR TITLE
Create ru_ru.json

### PR DESCRIPTION
**Pull request by Telezhka-the-First**

### CODE REVIEW

**Comment by Jamalam360** [comment]
@Telezhka-the-First was that intentional? If not I can copy the translations over manually

**Comment by Telezhka-the-First** [comment]
> @Telezhka-the-First was that intentional? If not I can copy the translations over manually

I just noticed that this mod is for Fabric, while I use Forge. Translations are correct. Yes, please, re-commit the translations.

**Comment by Jamalam360** [comment]
Alright thanks for them anyways! I'll get them committed tomorrow

**Comment by Jamalam360** [comment]
Alright thanks for them anyways! I'll get them committed tomorrow

**Comment by Telezhka-the-First** [comment]
> Alright thanks for them anyways! I'll get them committed tomorrow

😃

**Pull request closed without merging**
